'use client';

import { FormEvent, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Upload, Send, Wrench, CheckCircle2, Clock, RefreshCw } from 'lucide-react';

type Release = { id: string; versionName: string; versionCode: number; fileName: string; fileSizeBytes: number; status: string; releaseNotes?: string | null; publishedAt?: string | null; createdAt: string; downloadUrl: string };
type Data = { releases: Release[]; maintenance: { enabled: boolean; message?: string | null } };

export default function AdminAppReleasesPage() {
  const [data, setData] = useState<Data | null>(null);
  const [file, setFile] = useState<File | null>(null);
  const [versionName, setVersionName] = useState('');
  const [versionCode, setVersionCode] = useState('');
  const [releaseNotes, setReleaseNotes] = useState('');
  const [maintenanceEnabled, setMaintenanceEnabled] = useState(false);
  const [maintenanceMessage, setMaintenanceMessage] = useState('');
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const load = async () => { const response = await api.get('/app-releases/admin'); setData(response.data.data); setMaintenanceEnabled(response.data.data.maintenance.enabled); setMaintenanceMessage(response.data.data.maintenance.message || ''); };
  useEffect(() => { load().catch(() => setMessage('Unable to load app releases.')); }, []);
  const upload = async (event: FormEvent) => { event.preventDefault(); if (!file) return setMessage('Select an APK file first.'); setBusy(true); setMessage(''); try { const body = new FormData(); body.append('apk', file); body.append('versionName', versionName); body.append('versionCode', versionCode); body.append('releaseNotes', releaseNotes); await api.post('/app-releases/admin/upload', body, { headers: { 'Content-Type': 'multipart/form-data' } }); setMessage('APK uploaded as a draft. Publish it after testing.'); setFile(null); setVersionName(''); setVersionCode(''); setReleaseNotes(''); await load(); } catch (error: any) { setMessage(error?.response?.data?.message || 'APK upload failed.'); } finally { setBusy(false); } };
  const publish = async (id: string) => { setBusy(true); try { await api.post(`/app-releases/admin/${id}/publish`); setMessage('Release published and active residents notified.'); await load(); } catch (error: any) { setMessage(error?.response?.data?.message || 'Release could not be published.'); } finally { setBusy(false); } };
  const saveMaintenance = async () => { setBusy(true); try { await api.put('/app-releases/admin/maintenance', { enabled: maintenanceEnabled, message: maintenanceMessage }); setMessage('App maintenance status saved.'); await load(); } catch { setMessage('Maintenance status could not be saved.'); } finally { setBusy(false); } };
  return <main className="page" style={{ maxWidth: 1040, margin: '0 auto', padding: '24px 16px' }}><div style={{ marginBottom: 24 }}><p className="eyebrow">ADMINISTRATION</p><h1 className="pg-h">App Releases</h1><p style={{ color: 'var(--t2)', marginTop: 6 }}>Upload, test, publish, and maintain the official Legacy Homes Android APK.</p></div>{message && <div style={{ padding: 12, borderRadius: 10, background: 'var(--gl)', color: 'var(--t1)', marginBottom: 16 }}>{message}</div>}
    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(300px,1fr))', gap: 18, marginBottom: 20 }}><section className="card" style={{ padding: 20 }}><h2 style={{ fontSize: 16, color: 'var(--t1)', marginTop: 0 }}><Upload size={17} style={{ verticalAlign: 'middle', marginRight: 8 }} />Upload APK</h2><form onSubmit={upload} style={{ display: 'grid', gap: 12 }}><input type="file" accept=".apk,application/vnd.android.package-archive" onChange={(event) => setFile(event.target.files?.[0] || null)} required /><input className="input" placeholder="Version name, e.g. 1.0.1" value={versionName} onChange={(event) => setVersionName(event.target.value)} required /><input className="input" type="number" min="1" placeholder="Version code, e.g. 2" value={versionCode} onChange={(event) => setVersionCode(event.target.value)} required /><textarea className="input" placeholder="Release notes" value={releaseNotes} onChange={(event) => setReleaseNotes(event.target.value)} rows={4} /><button className="btn btn-primary" disabled={busy} type="submit">{busy ? <RefreshCw size={15} className="spin" /> : <Upload size={15} />} Upload as draft</button></form></section>
      <section className="card" style={{ padding: 20 }}><h2 style={{ fontSize: 16, color: 'var(--t1)', marginTop: 0 }}><Wrench size={17} style={{ verticalAlign: 'middle', marginRight: 8 }} />App maintenance</h2><p style={{ color: 'var(--t2)', fontSize: 13 }}>Show residents that the Android app is temporarily unavailable or being updated.</p><label style={{ display: 'flex', gap: 9, alignItems: 'center', color: 'var(--t1)', fontSize: 13 }}><input type="checkbox" checked={maintenanceEnabled} onChange={(event) => setMaintenanceEnabled(event.target.checked)} /> Maintenance is active</label><textarea className="input" style={{ marginTop: 14 }} placeholder="Maintenance message" value={maintenanceMessage} onChange={(event) => setMaintenanceMessage(event.target.value)} rows={4} /><button className="btn" style={{ marginTop: 12 }} disabled={busy} onClick={saveMaintenance}>Save status</button></section></div>
    <section className="card" style={{ padding: 20 }}><h2 style={{ fontSize: 16, color: 'var(--t1)', marginTop: 0 }}>Release history</h2>{!data ? <RefreshCw className="spin" /> : data.releases.length === 0 ? <p style={{ color: 'var(--t2)' }}>No APK releases uploaded yet.</p> : <div style={{ display: 'grid', gap: 10 }}>{data.releases.map((release) => <div key={release.id} style={{ border: '1px solid var(--bd)', borderRadius: 12, padding: 14, display: 'flex', gap: 12, justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap' }}><div><strong style={{ color: 'var(--t1)' }}>Version {release.versionName}</strong><span style={{ color: 'var(--t3)', marginLeft: 8 }}>code {release.versionCode} · {(release.fileSizeBytes / 1024 / 1024).toFixed(1)} MB</span><p style={{ margin: '5px 0 0', color: 'var(--t2)', fontSize: 12 }}>{release.releaseNotes || 'No release notes.'}</p></div><div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>{release.status === 'PUBLISHED' ? <span style={{ color: '#16a34a', fontSize: 12 }}><CheckCircle2 size={14} style={{ verticalAlign: 'middle' }} /> Published</span> : <><span style={{ color: 'var(--t3)', fontSize: 12 }}><Clock size={14} style={{ verticalAlign: 'middle' }} /> Draft</span><button className="btn btn-primary" disabled={busy} onClick={() => publish(release.id)}><Send size={14} /> Publish</button></>}</div></div>)}</div>}</section>
  </main>;
}
